"""
SQLAlchemy 2.0 ORM model for Report.
"""
from datetime import datetime
from decimal import Decimal
from typing import Optional

from sqlalchemy import ForeignKey, Integer, Numeric, String, Text, TIMESTAMP
from sqlalchemy.orm import relationship, Mapped, mapped_column

from app.shared.db import Base
from app.shared.time import now_utc


class Reporte(Base):
    """Report generated by a user"""
    __tablename__ = "reportes"
    
    id_reporte: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    id_usuario: Mapped[int] = mapped_column(ForeignKey("usuarios.id_usuario"), nullable=False)
    id_clip: Mapped[Optional[int]] = mapped_column(ForeignKey("clips.id_clip"))
    titulo: Mapped[Optional[str]] = mapped_column(String(200))
    descripcion: Mapped[Optional[str]] = mapped_column(Text)
    rango_fecha_inicio: Mapped[Optional[datetime]] = mapped_column(TIMESTAMP(timezone=True))
    rango_fecha_fin: Mapped[Optional[datetime]] = mapped_column(TIMESTAMP(timezone=True))
    filtro_confianza: Mapped[Optional[Decimal]] = mapped_column(Numeric(5, 2))
    tipo_evento: Mapped[Optional[str]] = mapped_column(String(50))
    fecha_generacion: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        default=now_utc
    )
    
    # Relationships
    usuario: Mapped["Usuario"] = relationship("Usuario", back_populates="reportes")
    clip: Mapped[Optional["Clip"]] = relationship("Clip", back_populates="reportes")

